url: https://zientziarengiltzak.github.io


# Site settings
title: Zientziaren Giltzak
logo:  zge.png
email: zientziarengiltzak@gmail.com
description: "Ondarroako Zientziaren Giltzak Elkartearen Webgunea."

future: false

# Team names, titles and social links
people:
- name: Jose Maria Argoitia
  pic: jmargoitia
  date: 1958-2016
  social:
    - title: info
      url: #Argoitia

- name: Eduardo Zabala
  pic: ezabala  

- name: Elixabete Garetxana
  pic: egaretxana

- name: Mario Feij√≥o
  pic: mfeijoo

- name: Nagore Elu
  pic: nelu

- name: Josu Ceberio
  pic: jceberio

- name: Carmen Lili
  pic: clili

- name: Edurne Aldape
  pic: ealdape

- name: Mikel Aizpuru
  pic: maizpuru

- name: Borja Calvo
  pic: bcalvo

- name: Nekane Akarregi
  pic: nakarregi

- name: Alberto Markuerkiaga
  pic: amarkuerkiaga

- name: Iker Badiola
  pic: ibadiola

- name: Leire Arantzamendi
  pic: larantzamendi

- name: Unai Ceberio
  pic: uceberio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ZientziaGiltzak
  - title: facebook
    url: https://www.facebook.com/people/Zientziaren-Giltzak/100011667360273
  - title: youtube
    url: https://www.youtube.com/channel/UCrcvhjRH2R2C4W2QNcKxMlg
  - title: flickr
    url: https://www.flickr.com/photos/borja_calvo/sets/72157672748367101

# Postal address (add as many lines as necessary)
address:
  - line: Postal Kutxa 33 48700 ONDARROA

errZenbakia: "AS/B/19168/2015" 
IFZ: "G95797486"

# Build settings
markdown: kramdown
permalink: pretty

remote_theme: y7kim/agency-jekyll-theme